// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Provisioning.proto

package org.whispersystems.signalservice.internal.push;

public final class ProvisioningProtos {
  private ProvisioningProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProvisionEnvelopeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:signalservice.ProvisionEnvelope)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes publicKey = 1;</code>
     */
    boolean hasPublicKey();
    /**
     * <code>optional bytes publicKey = 1;</code>
     */
    com.google.protobuf.ByteString getPublicKey();

    /**
     * <pre>
     * Encrypted ProvisionMessage
     * </pre>
     *
     * <code>optional bytes body = 2;</code>
     */
    boolean hasBody();
    /**
     * <pre>
     * Encrypted ProvisionMessage
     * </pre>
     *
     * <code>optional bytes body = 2;</code>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code signalservice.ProvisionEnvelope}
   */
  public  static final class ProvisionEnvelope extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:signalservice.ProvisionEnvelope)
      ProvisionEnvelopeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProvisionEnvelope.newBuilder() to construct.
    private ProvisionEnvelope(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProvisionEnvelope() {
      publicKey_ = com.google.protobuf.ByteString.EMPTY;
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProvisionEnvelope(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000001;
              publicKey_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              body_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.whispersystems.signalservice.internal.push.ProvisioningProtos.internal_static_signalservice_ProvisionEnvelope_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.whispersystems.signalservice.internal.push.ProvisioningProtos.internal_static_signalservice_ProvisionEnvelope_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope.class, org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope.Builder.class);
    }

    private int bitField0_;
    public static final int PUBLICKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString publicKey_;
    /**
     * <code>optional bytes publicKey = 1;</code>
     */
    public boolean hasPublicKey() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes publicKey = 1;</code>
     */
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString body_;
    /**
     * <pre>
     * Encrypted ProvisionMessage
     * </pre>
     *
     * <code>optional bytes body = 2;</code>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Encrypted ProvisionMessage
     * </pre>
     *
     * <code>optional bytes body = 2;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, publicKey_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(2, body_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, publicKey_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope)) {
        return super.equals(obj);
      }
      org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope other = (org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope) obj;

      if (hasPublicKey() != other.hasPublicKey()) return false;
      if (hasPublicKey()) {
        if (!getPublicKey()
            .equals(other.getPublicKey())) return false;
      }
      if (hasBody() != other.hasBody()) return false;
      if (hasBody()) {
        if (!getBody()
            .equals(other.getBody())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPublicKey()) {
        hash = (37 * hash) + PUBLICKEY_FIELD_NUMBER;
        hash = (53 * hash) + getPublicKey().hashCode();
      }
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code signalservice.ProvisionEnvelope}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:signalservice.ProvisionEnvelope)
        org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelopeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.whispersystems.signalservice.internal.push.ProvisioningProtos.internal_static_signalservice_ProvisionEnvelope_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.whispersystems.signalservice.internal.push.ProvisioningProtos.internal_static_signalservice_ProvisionEnvelope_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope.class, org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope.Builder.class);
      }

      // Construct using org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        publicKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        body_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.whispersystems.signalservice.internal.push.ProvisioningProtos.internal_static_signalservice_ProvisionEnvelope_descriptor;
      }

      @java.lang.Override
      public org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope getDefaultInstanceForType() {
        return org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope.getDefaultInstance();
      }

      @java.lang.Override
      public org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope build() {
        org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope buildPartial() {
        org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope result = new org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.publicKey_ = publicKey_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.body_ = body_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope) {
          return mergeFrom((org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope other) {
        if (other == org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope.getDefaultInstance()) return this;
        if (other.hasPublicKey()) {
          setPublicKey(other.getPublicKey());
        }
        if (other.hasBody()) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes publicKey = 1;</code>
       */
      public boolean hasPublicKey() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bytes publicKey = 1;</code>
       */
      public com.google.protobuf.ByteString getPublicKey() {
        return publicKey_;
      }
      /**
       * <code>optional bytes publicKey = 1;</code>
       */
      public Builder setPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        publicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes publicKey = 1;</code>
       */
      public Builder clearPublicKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        publicKey_ = getDefaultInstance().getPublicKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Encrypted ProvisionMessage
       * </pre>
       *
       * <code>optional bytes body = 2;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * Encrypted ProvisionMessage
       * </pre>
       *
       * <code>optional bytes body = 2;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <pre>
       * Encrypted ProvisionMessage
       * </pre>
       *
       * <code>optional bytes body = 2;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Encrypted ProvisionMessage
       * </pre>
       *
       * <code>optional bytes body = 2;</code>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:signalservice.ProvisionEnvelope)
    }

    // @@protoc_insertion_point(class_scope:signalservice.ProvisionEnvelope)
    private static final org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope();
    }

    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProvisionEnvelope>
        PARSER = new com.google.protobuf.AbstractParser<ProvisionEnvelope>() {
      @java.lang.Override
      public ProvisionEnvelope parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProvisionEnvelope(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProvisionEnvelope> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProvisionEnvelope> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionEnvelope getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProvisionMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:signalservice.ProvisionMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes identityKeyPublic = 1;</code>
     */
    boolean hasIdentityKeyPublic();
    /**
     * <code>optional bytes identityKeyPublic = 1;</code>
     */
    com.google.protobuf.ByteString getIdentityKeyPublic();

    /**
     * <code>optional bytes identityKeyPrivate = 2;</code>
     */
    boolean hasIdentityKeyPrivate();
    /**
     * <code>optional bytes identityKeyPrivate = 2;</code>
     */
    com.google.protobuf.ByteString getIdentityKeyPrivate();

    /**
     * <code>optional string number = 3;</code>
     */
    boolean hasNumber();
    /**
     * <code>optional string number = 3;</code>
     */
    java.lang.String getNumber();
    /**
     * <code>optional string number = 3;</code>
     */
    com.google.protobuf.ByteString
        getNumberBytes();

    /**
     * <code>optional string provisioningCode = 4;</code>
     */
    boolean hasProvisioningCode();
    /**
     * <code>optional string provisioningCode = 4;</code>
     */
    java.lang.String getProvisioningCode();
    /**
     * <code>optional string provisioningCode = 4;</code>
     */
    com.google.protobuf.ByteString
        getProvisioningCodeBytes();

    /**
     * <code>optional string userAgent = 5;</code>
     */
    boolean hasUserAgent();
    /**
     * <code>optional string userAgent = 5;</code>
     */
    java.lang.String getUserAgent();
    /**
     * <code>optional string userAgent = 5;</code>
     */
    com.google.protobuf.ByteString
        getUserAgentBytes();

    /**
     * <code>optional bytes profileKey = 6;</code>
     */
    boolean hasProfileKey();
    /**
     * <code>optional bytes profileKey = 6;</code>
     */
    com.google.protobuf.ByteString getProfileKey();

    /**
     * <code>optional bool readReceipts = 7;</code>
     */
    boolean hasReadReceipts();
    /**
     * <code>optional bool readReceipts = 7;</code>
     */
    boolean getReadReceipts();
  }
  /**
   * Protobuf type {@code signalservice.ProvisionMessage}
   */
  public  static final class ProvisionMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:signalservice.ProvisionMessage)
      ProvisionMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProvisionMessage.newBuilder() to construct.
    private ProvisionMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProvisionMessage() {
      identityKeyPublic_ = com.google.protobuf.ByteString.EMPTY;
      identityKeyPrivate_ = com.google.protobuf.ByteString.EMPTY;
      number_ = "";
      provisioningCode_ = "";
      userAgent_ = "";
      profileKey_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProvisionMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000001;
              identityKeyPublic_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              identityKeyPrivate_ = input.readBytes();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              number_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              provisioningCode_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              userAgent_ = bs;
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              profileKey_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              readReceipts_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.whispersystems.signalservice.internal.push.ProvisioningProtos.internal_static_signalservice_ProvisionMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.whispersystems.signalservice.internal.push.ProvisioningProtos.internal_static_signalservice_ProvisionMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage.class, org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage.Builder.class);
    }

    private int bitField0_;
    public static final int IDENTITYKEYPUBLIC_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString identityKeyPublic_;
    /**
     * <code>optional bytes identityKeyPublic = 1;</code>
     */
    public boolean hasIdentityKeyPublic() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes identityKeyPublic = 1;</code>
     */
    public com.google.protobuf.ByteString getIdentityKeyPublic() {
      return identityKeyPublic_;
    }

    public static final int IDENTITYKEYPRIVATE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString identityKeyPrivate_;
    /**
     * <code>optional bytes identityKeyPrivate = 2;</code>
     */
    public boolean hasIdentityKeyPrivate() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes identityKeyPrivate = 2;</code>
     */
    public com.google.protobuf.ByteString getIdentityKeyPrivate() {
      return identityKeyPrivate_;
    }

    public static final int NUMBER_FIELD_NUMBER = 3;
    private volatile java.lang.Object number_;
    /**
     * <code>optional string number = 3;</code>
     */
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string number = 3;</code>
     */
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          number_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string number = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROVISIONINGCODE_FIELD_NUMBER = 4;
    private volatile java.lang.Object provisioningCode_;
    /**
     * <code>optional string provisioningCode = 4;</code>
     */
    public boolean hasProvisioningCode() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string provisioningCode = 4;</code>
     */
    public java.lang.String getProvisioningCode() {
      java.lang.Object ref = provisioningCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          provisioningCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string provisioningCode = 4;</code>
     */
    public com.google.protobuf.ByteString
        getProvisioningCodeBytes() {
      java.lang.Object ref = provisioningCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        provisioningCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERAGENT_FIELD_NUMBER = 5;
    private volatile java.lang.Object userAgent_;
    /**
     * <code>optional string userAgent = 5;</code>
     */
    public boolean hasUserAgent() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string userAgent = 5;</code>
     */
    public java.lang.String getUserAgent() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userAgent_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userAgent = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUserAgentBytes() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROFILEKEY_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString profileKey_;
    /**
     * <code>optional bytes profileKey = 6;</code>
     */
    public boolean hasProfileKey() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional bytes profileKey = 6;</code>
     */
    public com.google.protobuf.ByteString getProfileKey() {
      return profileKey_;
    }

    public static final int READRECEIPTS_FIELD_NUMBER = 7;
    private boolean readReceipts_;
    /**
     * <code>optional bool readReceipts = 7;</code>
     */
    public boolean hasReadReceipts() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional bool readReceipts = 7;</code>
     */
    public boolean getReadReceipts() {
      return readReceipts_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, identityKeyPublic_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(2, identityKeyPrivate_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, number_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, provisioningCode_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, userAgent_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeBytes(6, profileKey_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeBool(7, readReceipts_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, identityKeyPublic_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, identityKeyPrivate_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, number_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, provisioningCode_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, userAgent_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, profileKey_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, readReceipts_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage)) {
        return super.equals(obj);
      }
      org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage other = (org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage) obj;

      if (hasIdentityKeyPublic() != other.hasIdentityKeyPublic()) return false;
      if (hasIdentityKeyPublic()) {
        if (!getIdentityKeyPublic()
            .equals(other.getIdentityKeyPublic())) return false;
      }
      if (hasIdentityKeyPrivate() != other.hasIdentityKeyPrivate()) return false;
      if (hasIdentityKeyPrivate()) {
        if (!getIdentityKeyPrivate()
            .equals(other.getIdentityKeyPrivate())) return false;
      }
      if (hasNumber() != other.hasNumber()) return false;
      if (hasNumber()) {
        if (!getNumber()
            .equals(other.getNumber())) return false;
      }
      if (hasProvisioningCode() != other.hasProvisioningCode()) return false;
      if (hasProvisioningCode()) {
        if (!getProvisioningCode()
            .equals(other.getProvisioningCode())) return false;
      }
      if (hasUserAgent() != other.hasUserAgent()) return false;
      if (hasUserAgent()) {
        if (!getUserAgent()
            .equals(other.getUserAgent())) return false;
      }
      if (hasProfileKey() != other.hasProfileKey()) return false;
      if (hasProfileKey()) {
        if (!getProfileKey()
            .equals(other.getProfileKey())) return false;
      }
      if (hasReadReceipts() != other.hasReadReceipts()) return false;
      if (hasReadReceipts()) {
        if (getReadReceipts()
            != other.getReadReceipts()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIdentityKeyPublic()) {
        hash = (37 * hash) + IDENTITYKEYPUBLIC_FIELD_NUMBER;
        hash = (53 * hash) + getIdentityKeyPublic().hashCode();
      }
      if (hasIdentityKeyPrivate()) {
        hash = (37 * hash) + IDENTITYKEYPRIVATE_FIELD_NUMBER;
        hash = (53 * hash) + getIdentityKeyPrivate().hashCode();
      }
      if (hasNumber()) {
        hash = (37 * hash) + NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getNumber().hashCode();
      }
      if (hasProvisioningCode()) {
        hash = (37 * hash) + PROVISIONINGCODE_FIELD_NUMBER;
        hash = (53 * hash) + getProvisioningCode().hashCode();
      }
      if (hasUserAgent()) {
        hash = (37 * hash) + USERAGENT_FIELD_NUMBER;
        hash = (53 * hash) + getUserAgent().hashCode();
      }
      if (hasProfileKey()) {
        hash = (37 * hash) + PROFILEKEY_FIELD_NUMBER;
        hash = (53 * hash) + getProfileKey().hashCode();
      }
      if (hasReadReceipts()) {
        hash = (37 * hash) + READRECEIPTS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getReadReceipts());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code signalservice.ProvisionMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:signalservice.ProvisionMessage)
        org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.whispersystems.signalservice.internal.push.ProvisioningProtos.internal_static_signalservice_ProvisionMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.whispersystems.signalservice.internal.push.ProvisioningProtos.internal_static_signalservice_ProvisionMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage.class, org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage.Builder.class);
      }

      // Construct using org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        identityKeyPublic_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        identityKeyPrivate_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        number_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        provisioningCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        userAgent_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        profileKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        readReceipts_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.whispersystems.signalservice.internal.push.ProvisioningProtos.internal_static_signalservice_ProvisionMessage_descriptor;
      }

      @java.lang.Override
      public org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage getDefaultInstanceForType() {
        return org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage.getDefaultInstance();
      }

      @java.lang.Override
      public org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage build() {
        org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage buildPartial() {
        org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage result = new org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.identityKeyPublic_ = identityKeyPublic_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.identityKeyPrivate_ = identityKeyPrivate_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.number_ = number_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.provisioningCode_ = provisioningCode_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.userAgent_ = userAgent_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.profileKey_ = profileKey_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.readReceipts_ = readReceipts_;
          to_bitField0_ |= 0x00000040;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage) {
          return mergeFrom((org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage other) {
        if (other == org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage.getDefaultInstance()) return this;
        if (other.hasIdentityKeyPublic()) {
          setIdentityKeyPublic(other.getIdentityKeyPublic());
        }
        if (other.hasIdentityKeyPrivate()) {
          setIdentityKeyPrivate(other.getIdentityKeyPrivate());
        }
        if (other.hasNumber()) {
          bitField0_ |= 0x00000004;
          number_ = other.number_;
          onChanged();
        }
        if (other.hasProvisioningCode()) {
          bitField0_ |= 0x00000008;
          provisioningCode_ = other.provisioningCode_;
          onChanged();
        }
        if (other.hasUserAgent()) {
          bitField0_ |= 0x00000010;
          userAgent_ = other.userAgent_;
          onChanged();
        }
        if (other.hasProfileKey()) {
          setProfileKey(other.getProfileKey());
        }
        if (other.hasReadReceipts()) {
          setReadReceipts(other.getReadReceipts());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString identityKeyPublic_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes identityKeyPublic = 1;</code>
       */
      public boolean hasIdentityKeyPublic() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bytes identityKeyPublic = 1;</code>
       */
      public com.google.protobuf.ByteString getIdentityKeyPublic() {
        return identityKeyPublic_;
      }
      /**
       * <code>optional bytes identityKeyPublic = 1;</code>
       */
      public Builder setIdentityKeyPublic(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        identityKeyPublic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes identityKeyPublic = 1;</code>
       */
      public Builder clearIdentityKeyPublic() {
        bitField0_ = (bitField0_ & ~0x00000001);
        identityKeyPublic_ = getDefaultInstance().getIdentityKeyPublic();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString identityKeyPrivate_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes identityKeyPrivate = 2;</code>
       */
      public boolean hasIdentityKeyPrivate() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bytes identityKeyPrivate = 2;</code>
       */
      public com.google.protobuf.ByteString getIdentityKeyPrivate() {
        return identityKeyPrivate_;
      }
      /**
       * <code>optional bytes identityKeyPrivate = 2;</code>
       */
      public Builder setIdentityKeyPrivate(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        identityKeyPrivate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes identityKeyPrivate = 2;</code>
       */
      public Builder clearIdentityKeyPrivate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        identityKeyPrivate_ = getDefaultInstance().getIdentityKeyPrivate();
        onChanged();
        return this;
      }

      private java.lang.Object number_ = "";
      /**
       * <code>optional string number = 3;</code>
       */
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string number = 3;</code>
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            number_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string number = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string number = 3;</code>
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string number = 3;</code>
       */
      public Builder clearNumber() {
        bitField0_ = (bitField0_ & ~0x00000004);
        number_ = getDefaultInstance().getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional string number = 3;</code>
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        number_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object provisioningCode_ = "";
      /**
       * <code>optional string provisioningCode = 4;</code>
       */
      public boolean hasProvisioningCode() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string provisioningCode = 4;</code>
       */
      public java.lang.String getProvisioningCode() {
        java.lang.Object ref = provisioningCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            provisioningCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string provisioningCode = 4;</code>
       */
      public com.google.protobuf.ByteString
          getProvisioningCodeBytes() {
        java.lang.Object ref = provisioningCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          provisioningCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string provisioningCode = 4;</code>
       */
      public Builder setProvisioningCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        provisioningCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string provisioningCode = 4;</code>
       */
      public Builder clearProvisioningCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        provisioningCode_ = getDefaultInstance().getProvisioningCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string provisioningCode = 4;</code>
       */
      public Builder setProvisioningCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        provisioningCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userAgent_ = "";
      /**
       * <code>optional string userAgent = 5;</code>
       */
      public boolean hasUserAgent() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string userAgent = 5;</code>
       */
      public java.lang.String getUserAgent() {
        java.lang.Object ref = userAgent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userAgent_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userAgent = 5;</code>
       */
      public com.google.protobuf.ByteString
          getUserAgentBytes() {
        java.lang.Object ref = userAgent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userAgent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userAgent = 5;</code>
       */
      public Builder setUserAgent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        userAgent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userAgent = 5;</code>
       */
      public Builder clearUserAgent() {
        bitField0_ = (bitField0_ & ~0x00000010);
        userAgent_ = getDefaultInstance().getUserAgent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userAgent = 5;</code>
       */
      public Builder setUserAgentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        userAgent_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString profileKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes profileKey = 6;</code>
       */
      public boolean hasProfileKey() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional bytes profileKey = 6;</code>
       */
      public com.google.protobuf.ByteString getProfileKey() {
        return profileKey_;
      }
      /**
       * <code>optional bytes profileKey = 6;</code>
       */
      public Builder setProfileKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        profileKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes profileKey = 6;</code>
       */
      public Builder clearProfileKey() {
        bitField0_ = (bitField0_ & ~0x00000020);
        profileKey_ = getDefaultInstance().getProfileKey();
        onChanged();
        return this;
      }

      private boolean readReceipts_ ;
      /**
       * <code>optional bool readReceipts = 7;</code>
       */
      public boolean hasReadReceipts() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional bool readReceipts = 7;</code>
       */
      public boolean getReadReceipts() {
        return readReceipts_;
      }
      /**
       * <code>optional bool readReceipts = 7;</code>
       */
      public Builder setReadReceipts(boolean value) {
        bitField0_ |= 0x00000040;
        readReceipts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool readReceipts = 7;</code>
       */
      public Builder clearReadReceipts() {
        bitField0_ = (bitField0_ & ~0x00000040);
        readReceipts_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:signalservice.ProvisionMessage)
    }

    // @@protoc_insertion_point(class_scope:signalservice.ProvisionMessage)
    private static final org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage();
    }

    public static org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProvisionMessage>
        PARSER = new com.google.protobuf.AbstractParser<ProvisionMessage>() {
      @java.lang.Override
      public ProvisionMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProvisionMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProvisionMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProvisionMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.whispersystems.signalservice.internal.push.ProvisioningProtos.ProvisionMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signalservice_ProvisionEnvelope_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signalservice_ProvisionEnvelope_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_signalservice_ProvisionMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_signalservice_ProvisionMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Provisioning.proto\022\rsignalservice\"4\n\021P" +
      "rovisionEnvelope\022\021\n\tpublicKey\030\001 \001(\014\022\014\n\004b" +
      "ody\030\002 \001(\014\"\260\001\n\020ProvisionMessage\022\031\n\021identi" +
      "tyKeyPublic\030\001 \001(\014\022\032\n\022identityKeyPrivate\030" +
      "\002 \001(\014\022\016\n\006number\030\003 \001(\t\022\030\n\020provisioningCod" +
      "e\030\004 \001(\t\022\021\n\tuserAgent\030\005 \001(\t\022\022\n\nprofileKey" +
      "\030\006 \001(\014\022\024\n\014readReceipts\030\007 \001(\010BD\n.org.whis" +
      "persystems.signalservice.internal.pushB\022" +
      "ProvisioningProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_signalservice_ProvisionEnvelope_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_signalservice_ProvisionEnvelope_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signalservice_ProvisionEnvelope_descriptor,
        new java.lang.String[] { "PublicKey", "Body", });
    internal_static_signalservice_ProvisionMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_signalservice_ProvisionMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_signalservice_ProvisionMessage_descriptor,
        new java.lang.String[] { "IdentityKeyPublic", "IdentityKeyPrivate", "Number", "ProvisioningCode", "UserAgent", "ProfileKey", "ReadReceipts", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
